name: authentication_repository


environment:
  sdk: ^3.5.0

dev_dependencies:
  flutter_lints: ^4.0.0

dependencies:
  formz: ^0.4.1
  firebase_auth: ^5.2.0
  google_sign_in: ^6.0.2
  equatable: ^2.0.5
  